"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Search, SearchCreate, SearchUpdate
from .store import store

app = FastAPI(
    title="Tutorial Engineering Knowledge Search API",
    version="0.1.0",
    description="REST API for Tutorial Engineering Knowledge Search. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "searches", "description": "Searches managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/searches", response_model=List[Search], tags=["searches"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/searches", response_model=Search, status_code=201, tags=["searches"])
def create_item(body: SearchCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/searches/{item_id}", response_model=Search, tags=["searches"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Search not found")
    return item


@app.patch("/api/searches/{item_id}", response_model=Search, tags=["searches"])
def update_item(item_id: int, body: SearchUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Search not found")
    return item


@app.delete("/api/searches/{item_id}", status_code=204, tags=["searches"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Search not found")
